config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :diaries
    end
  end

  resources :diaries, only: [:new, :create]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :send_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true                  
  has_secure_password
  
  has_many :diaries
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def follower?(other_user)
    self.followers.include?(other_user)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :require_user_logged_in
  
  def new
    @diary = Diary.new
  end

  def create
    @diary = current_user.diaries.build(diary_params)
    @diary.send_id = params[:send_id]
    if @diary.save
      flash[:warning] = '日記を更新しました。'
      redirect_to diaries_user_path(@diary.send_id)
    else
      @diaries = current_user.diaries.order('created_at DESC').page(params[:page])
      flash.now[:warning] = '日記の更新に失敗しました。'
      render :new
    end
  end
  
  private

  def diary_params
    params.require(:diary).permit(:content)
  end
  
  def the_two_diaries(sender, receiver)
    sender.diaries.where(send_id: receiver.id) + receiver.diaries.where(send_id: sender.id).order('created_at DESC').page(params[:page])
  end

  def debug_params
    puts "********begin************"
    p params
    puts "********end**************"
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:warning] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:warning] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all.page(params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    @followers = @user.followers.page(params[:page])
    p followings_followers_ids = @user.followings.pluck(:id) + @user.followers.pluck(:id).group_by{|i| i}.reject{|k,v| v.one?}.keys
    @followings_followers = User.where(id: followings_followers_ids).page(params[:page])
    @last_diary = Diary.where(id: the_two_diaries(current_user, @user).pluck(:id)).order('updated_at DESC').first
    @diaries = Diary.where(id: the_two_diaries(current_user, @user).pluck(:id)).order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:warning] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:warning] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:warning] = 'プロフィールを更新しました'
      redirect_to @user
    else
      flash.now[:warning] = 'プロフィールの更新に失敗しました。'
      render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
  end
  
  def diaries
    @user = User.find(params[:id])
    @diaries = Diary.where(id: the_two_diaries(current_user, @user).pluck(:id)).order('created_at ASC')
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def the_two_diaries(sender, receiver)
    sender.diaries.where(send_id: receiver.id) + receiver.diaries.where(send_id: sender.id).order('created_at ASC').page(params[:page])
  end
  
  def correct_user
    user = User.find(params[:id])
    @user = current_user.id == user.id
    unless @user
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/diaries/new.html.erb
<div class="row">
  <div class="col-xs-offset-2 col-xs-8">
    <div class="panel panel-default">
      <div class="panel-heading">交換日記を書く</div>
      <div class="panel-body">
        <%= form_for(@diary) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <%= hidden_field_tag :send_id, params[:send_id] %>
          <div class="form-group">
            <%= f.label :content, '日記' %>
            <%= f.text_area :content, class: 'form-control', rows: 10 %>
          </div>
          <div class="text-right">
            <%= button_tag(class: "btn btn-brown200_rsd") do %>
              <%= content_tag :span, "日記を書く", class: "glyphicon glyphicon-pencil" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/diaries/show.html.erb
<h1>Diaries#show</h1>
<p>Find me in app/views/diaries/show.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2017 SECRET DIARY.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Secret Diary</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to '相手を探す', users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
            <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'マイページ', user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>  
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Secret Diary</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.rawgit.com/maechabin/bootstrap-material-button-color/master/dist/cb-materialbtn.0.5.5.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    
    <%= yield :cover %>  
    

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローを外す', class: 'btn btn-brown500_flt' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローする', class: 'btn btn-teal700_rsd' %>
    <% end %>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>本当の気持ちをこの場所で</h1>
        <% unless logged_in? %>
         <%= link_to "交換日記を始める", signup_path, class: "btn btn-default btn-lg" %>
        <% end %> 
      </div>
    </div>
  </div>
  <div class="top-wrapper">
    <div class="container text-center">
      <h2>CONCEPT...</h2>
      <h3>いつも話せないことを交換日記で話そう。</h3>
      <p>近年SNSが大きく普及し、世界中の人と繋がることが出来る時代になりました。</p>
      <p>しかしこの様な便利な時代だからこそ、大切な人に本当の気持ちを伝えづらくなってしまったのではないでしょうか。</p>
      <p>この場所は、そんな大切な人と普段話せない話が出来る場所として是非活用して欲しいと思います。</p>
    </div>
  </div>
  <div class="message-wrapper">
    <div class="container text-center">
      <h2>HOW TO USE...</h2>
      <h3>交換日記をしたい人をフォローしよう。</h3>
      <p>この交換日記はお互いがフォローしなければ交換日記を書くことはできません。</p>
      <p>お互いのフォローが成立したら「交換日記が出来る相手」の下にユーザの名前が現れます</p>
      <p>ユーザの名前を押してみると…</p>
    </div>
  </div>  
  <div class="container" id="start">
    <div class="text-center">
      <h3>さっそく始めよう！</h3>
      <% unless logged_in? %>
        <%= link_to "交換日記を始める", signup_path, class: "btn btn-brown900_rsd btn-lg" %>
      <% end %>  
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <div>
    <% users.each do |user| %>
      <div>
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div>
            <div>
              <img class="img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
            </div>
            <div>
              <div class="user">
                <%= link_to(user.name, user_path(user), class: "link") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate users %>
<% end %>

app/views/users/diaries.html.erb
<div id="magazine">
  <div class="hard"> 
    <h1>Secret Diary</h1> 
  </div>
  <div class="hard"></div>
  <div class="text-center">
    <h2>交換日記へようこそ！</h2>
    <h4>
      <br>
      交換日記は一方的な投稿はできません！<br>
      必ず相手の反応があってこその交換日記です。<br>
      <br>
      普段話しづらいことや、悩みを話すのも良し、<br>
      今日あったことを話すのも良し、<br>
      明日のことを話すのも良しです！<br>
      <br>
      使い方は自由です！<br>
      <br>
      是非上手に活用してください！<br>
      <br>
      ページをめくって書いた日記を見てみよう。<br>
    </h4>
  </div>
  <% @diaries.each do |diary| %>
    <% user = User.find(diary.user_id) %>
    <div>
      <h5>
      	<img class="img-rounded" src="<%= gravatar_url(user, options = { size: 50 }) %>" alt=""><br>
      	<%= link_to user.name, user_path(user) %><br>
      	<span class="text-muted">日記更新日 <%= diary.created_at %></span>
      </h5>
      <h4>
        <%= diary.content %>
      </h4>  
    </div>	
  <% end %>
	<div class="text-center" id="end">
	  <h4>
	    今日もお疲れさまでした。<br>
	    明日もいい日になりますように...
	  </h4>
	</div>
  <div class="hard"></div>
</div>

<script type="text/javascript">
	$(function() {
		$('#magazine').turn({
							display: 'double',
							acceleration: true,
							gradients: !$.isTouch,
							elevation:50,
							when: {
								turned: function(e, page) {
									/*console.log('Current view: ', $(this).turn('view'));*/
								}
							},
							turnCorners: "tl,tr"
						});
	});
	
	
	$(window).bind('keydown', function(e){
		
		if (e.keyCode==37)
			$('#magazine').turn('previous');
		else if (e.keyCode==39)
			$('#magazine').turn('next');
			
	});
</script>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-offset-2 col-xs-8">
    <div class="panel panel-default">
      <div class="panel-heading">プロフィール編集</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '更新する', class: "btn btn-grey900_rsd" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<%= render 'users', users: @followers %>

app/views/users/followings.html.erb
<%= render 'users', users: @followings %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-2 col-xs-8">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: "btn btn-grey900_rsd" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h2><%= @user.name %></h2>
  </div>
  <% if current_user.id == @user.id %>
    <div class="text-center" id="edit">
      <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-grey700_rsd"%>
    </div>
    <div class="text-center" id="follow">
      <%= link_to "フォロー", followings_user_path(@user), class: "btn btn-grey100_rsd"%>
      <%= link_to "フォロワー", followers_user_path(@user), class: "btn btn-grey100_rsd"%>  
    </div>
    
    <div class="text-center">
      <span class="glyphicon glyphicon-book" aria-hidden="true" id="icon"></span>
      <h3>
        交換日記ができる相手
      </h3>
    </div>
    <div class="text-center" id="followings_followers">
      <%= render 'users', users: @followings_followers %>
    </div>
  <% end %>
  <div class="text-center">
    <%= render 'relationships/follow_button', user: @user %>
  </div>
  
  <% if current_user.id != @user.id && current_user.following?(@user) && current_user.follower?(@user)%>
    <div class="text-center" id="desk">
      <% if @diaries.blank? || @last_diary && @last_diary.user_id != current_user.id %>
        <%= link_to new_diary_path(send_id: @user.id), class: 'btn btn-brown200_rsd' do %>
          <i class='glyphicon glyphicon-pencil'></i> 日記を書く
        <% end %>
      <% else %>
        <div class='btn btn-grey100_rsd'>返信待ち...</div>
      <% end %>
      <%= link_to diaries_user_path(@user), class: 'btn btn-brown700_rsd' do %>
        <i class='glyphicon glyphicon-book'></i> 交換日記を見る
      <% end %>
    </div>
  <% end %>
</div>

  
  